server:
  port: 7070

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Henyelrey/PDAD.git
          search-paths: config-data
          default-label: ms-config-server

  security:
    user:
      name: root
      password: s3cr3t
